#!/bin/sh
set -e

if [ $# -lt 1 ]; then
  echo "usage: ./run <program.lisp>" >&2
  exit 1
fi

dir="$(cd "$(dirname "$0")" && pwd)"
src="$(realpath "$1")"
bin="${src%.lisp}.bin"

cd "$dir/compiler"
scryer-prolog -f -g "use_module(compiler), compile_file('$src', '$bin'), halt." < /dev/null

shift
exec "$dir/vm" "$bin" "$@"
