#!/bin/sh
set -e

if [ $# -lt 1 ]; then
  echo "usage: ./run <program.lisp>" >&2
  exit 1
fi

src="$1"
bin="${src%.lisp}.bin"

cd compiler
scryer-prolog -f -g "use_module(compiler), compile_file('../$src', '../$bin'), halt." < /dev/null
cd ..

shift
exec ./vm "$bin" "$@"
